# Zorix OS touchpad policy
# Touchpads stay on libinput. Wacom is installed separately for real tablets/styli.
Section "InputClass"
    Identifier "Zorix touchpad"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "Tapping" "on"
    Option "TappingDrag" "on"
    Option "TappingDragLock" "off"
    Option "DisableWhileTyping" "on"
    Option "NaturalScrolling" "false"
    Option "ScrollMethod" "twofinger"
    Option "AccelProfile" "adaptive"
    Option "AccelSpeed" "0.00"
    Option "HorizontalScrolling" "true"
    Option "TappingButtonMap" "lrm"
EndSection

Section "InputClass"
    Identifier "Zorix touchscreen"
    MatchIsTouchscreen "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
EndSection
