/* SPDX-License-Identifier: MIT */
'use strict';
const paths={
 folder:'M3 7h6l2 2h10v11H3z M3 7V5h6l2 2',compass:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M16 8l-3 5-5 3 3-5z',note:'M5 3h14v18H5z M8 8h8 M8 12h8 M8 16h5',chip:'M6 6h12v12H6z M9 9h6v6H9z M9 2v4 M15 2v4 M9 18v4 M15 18v4 M2 9h4 M2 15h4 M18 9h4 M18 15h4',terminal:'M3 5h18v14H3z M7 9l3 3-3 3 M12 15h5',sparkle:'M12 2l2.7 7.3L22 12l-7.3 2.7L12 22l-2.7-7.3L2 12l7.3-2.7z',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M10 2h4l1 3 3 1 3 1v4l-2 2 1 3-3 3-3-1-2 2H9l-1-3-3-1-3-1v-4l2-2-1-3 3-3 3 1z',grid:'M3 3h6v6H3z M15 3h6v6h-6z M3 15h6v6H3z M15 15h6v6h-6z',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6',sliders:'M3 6h8 M16 6h5 M3 18h5 M13 18h8 M11 3v6 M16 12v0 M8 15v6 M3 12h18',arrow:'M4 12h15 M14 7l5 5-5 5',moon:'M20 14A8.5 8.5 0 0 1 10 4a8.5 8.5 0 1 0 10 10',shield:'M12 2l8 3v7c0 5-8 10-8 10S4 17 4 12V5z M8 12l3 3 5-6',calculator:'M5 2h14v20H5z M8 5h8v4H8z M8 13h1 M15 13h1 M8 17h1 M15 17h1',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 6v6l4 3',info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 10v7 M12 7v0',power:'M12 2v10 M6 5a9 9 0 1 0 12 0',file:'M6 2h8l4 4v16H6z M14 2v5h4',check:'M4 12l5 5L20 6',pulse:'M3 12h4l2-6 4 12 2-6h6',code:'M8 7l-5 5 5 5 M16 7l5 5-5 5 M14 4l-4 16',droplet:'M12 2s7 7.2 7 12a7 7 0 0 1-14 0c0-4.8 7-12 7-12z',trash:'M5 7h14 M9 7V4h6v3 M7 7l1 14h8l1-14',layers:'M12 3l9 5-9 5-9-5z M3 12l9 5 9-5 M3 16l9 5 9-5',cpu:'M8 8h8v8H8z M9 2v3 M15 2v3 M9 19v3 M15 19v3 M2 9h3 M2 15h3 M19 9h3 M19 15h3',wifi:'M4 10a12 12 0 0 1 16 0 M7 13a8 8 0 0 1 10 0 M10 16a4 4 0 0 1 4 0 M12 20h0',bluetooth:'M7 7l10 10-5 4V3l5 4L7 17',volume:'M4 10h4l5-4v12l-5-4H4z M16 9a5 5 0 0 1 0 6 M18 6a9 9 0 0 1 0 12',battery:'M5 7h13v10H5z M18 10h2v4h-2 M7 9h7v6H7z',edit:'M5 4h10l4 4v12H5z M8 16l1-4 7-7 3 3-7 7z',image:'M4 5h16v14H4z M7 15l3-4 3 3 2-2 3 3 M9 9h0',archive:'M5 3h14v18H5z M5 8h14 M10 11h4v4h-4z',monitor:'M3 5h18v13H3z M8 21h8 M12 18v3 M6 13h3l2-5 2 7 2-4 3 2',software:'M5 4h14l2 5-2 11H5L3 9z M3 9h18 M9 13h6',media:'M6 4l13 8-13 8z'};
const iconThemes={folder:['#5fa6ff','#356cf4'],compass:['#62e8ef','#188db8'],note:['#ffd27b','#d59138'],check:['#74edc6','#2da684'],chip:['#b79cff','#775ee4'],terminal:['#435264','#141c26'],grid:['#eef4fa','#93a0af'],sparkle:['#ffb0d0','#d2669d'],settings:['#b6c0ca','#69727f'],pulse:['#6dcbff','#4a7cf3'],calculator:['#69ddeb','#1594ae'],moon:['#b79cff','#7d67df'],clock:['#7fe6cc','#34b590'],info:['#73c1ff','#3e7ef8'],shield:['#79ebc8','#2ca57d'],droplet:['#70e8ee','#1ea9d6'],code:['#7eedcd','#36b892'],layers:['#b9c2ce','#6d7684'],search:['#eef4fa','#93a0af'],file:['#b7c3d3','#7d8896'],edit:['#ffb36d','#d66f55'],image:['#68d7ff','#5c73ed'],archive:['#e8b86c','#a96e39'],monitor:['#6fd7b5','#318e78'],software:['#8bc3ff','#596fe4'],media:['#ff8eb9','#b95788']};
const filledSymbols=new Set(['sparkle','grid']);
function icon(k, cls=''){return `<svg viewBox="0 0 24 24" aria-hidden="true" class="${cls}"><path d="${paths[k]||paths.grid}"/></svg>`}
function appIconSVG(k){const [c1,c2]=(iconThemes[k]||['#93a0af','#506070']);const fill=filledSymbols.has(k)?' fill':'';return `<svg class="app-badge-svg" viewBox="0 0 64 64" aria-hidden="true"><defs><linearGradient id="g-${k}" x1="12" y1="10" x2="54" y2="56" gradientUnits="userSpaceOnUse"><stop offset="0%" stop-color="${c1}"/><stop offset="100%" stop-color="${c2}"/></linearGradient><linearGradient id="glassShine" x1="8" y1="8" x2="48" y2="48" gradientUnits="userSpaceOnUse"><stop offset="0%" stop-color="rgba(255,255,255,.95)"/><stop offset="100%" stop-color="rgba(255,255,255,0)"/></linearGradient></defs><rect x="6" y="6" width="52" height="52" rx="16" fill="url(#g-${k})"/><rect class="frame" x="6.5" y="6.5" width="51" height="51" rx="15.5" fill="none"/><path class="shine" d="M16 11h29c4.4 0 8 3.6 8 8v3c-4.7-3.8-9.6-5.8-15.7-5.8H16.2C11.9 16.2 9 18.5 7 21v-2c0-4.4 3.6-8 8-8Z"/><path class="symbol${fill}" d="${paths[k]||paths.grid}" transform="translate(8 8) scale(2)"/></svg>`}
function icons(){document.querySelectorAll('[data-icon]').forEach(e=>{if(e.classList.contains('appicon')||e.classList.contains('desktop-glyph'))e.innerHTML=appIconSVG(e.dataset.icon);else e.innerHTML=icon(e.dataset.icon)})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const hashParams=new URLSearchParams(location.hash.slice(1));
const token=hashParams.get('token')||sessionStorage.getItem('zorix-token')||'';
const renderMode=hashParams.get('render')||'native';
document.documentElement.dataset.render=renderMode;
try{if(token)sessionStorage.setItem('zorix-token',token);history.replaceState(null,'',location.pathname)}catch{}
let settings={},system={},connectivity={},discoveredApps=[],currentPanel='',currentPath='',currentFileRoot='home',currentSettingsSection='appearance',toastTimer,focusRemaining=1500,focusRunning=false,focusDeadline=0,calc='';
const $=s=>document.querySelector(s), titles={launcher:'Applications',files:'Zorix Files',notes:'Zorix Notes',tasks:'Flow Board',settings:'Settings',control:'Control Center',compatibility:'Play & Compatibility',system:'System Information',performance:'Live Activity',activity:'Recent Activity',glasslab:'Glass Lab',rustlab:'Rust Layer',about:'About Zorix',focus:'Focus Space',calculator:'Calculator',calendar:'Calendar',welcome:'Welcome to Zorix',support:'Support & Recovery'};
async function api(path,data){const opt={headers:{'X-Zorix-Token':token}};if(data!==undefined){opt.method='POST';opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(data)}const r=await fetch('/api/'+path,opt);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function reportStartupError(kind,error){try{fetch('/api/client-error',{method:'POST',headers:{'X-Zorix-Token':token,'Content-Type':'application/json'},body:JSON.stringify({kind,message:String(error?.message||error),stack:String(error?.stack||'').slice(0,1200)})})}catch{}}
window.addEventListener('error',e=>reportStartupError('error',e.error||e.message));
window.addEventListener('unhandledrejection',e=>reportStartupError('rejection',e.reason));
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),3500)}
function applySettings(){document.body.classList.toggle('dawn',settings.theme==='dawn');document.body.classList.toggle('midnight',settings.theme==='midnight');document.body.classList.toggle('opaque',!!settings.reducedTransparency);document.body.classList.toggle('reduced-motion',!!settings.reducedMotion);document.body.classList.toggle('high-contrast',!!settings.contrast);document.body.classList.toggle('large-text',!!settings.largeText);document.body.classList.toggle('no-wallpaper-motion',settings.wallpaperMotion===false);document.documentElement.lang=settings.language||'en';const g=Number(settings.glassIntensity||64);document.documentElement.style.setProperty('--glass-opacity',String(Math.max(.42,Math.min(.82,g/100))));document.documentElement.style.setProperty('--glass-blur',`${Math.round(8+g*.12)}px`)}
async function updateSettings(d){settings=await api('settings',d);applySettings();return settings}
async function launch(app){try{const r=await api('launch',{app});toast(r.testMode?'Launch checked (test mode)':`Opening ${app}...`)}catch(e){toast(e.message)}}
const builtInApps=[['files','folder','blue','Files','Browse your home'],['browser','compass','cyan','Browser','Open the web',true],['notes','note','amber','Notes','Capture an idea'],['tasks','check','mint','Flow Board','Small local tasks'],['text','edit','amber','Text Editor','Edit local text files',true],['image','image','blue','Images','View local images',true],['archive','archive','amber','Archive Manager','Inspect and safely extract archives',true],['media','media','rose','Media','Open local audio and video',true],['terminal','terminal','dark','Terminal','Your command line',true],['software','software','blue','Software Center','Search packages and install with ZPK',true],['monitor','monitor','mint','System Monitor','Processes, load and memory',true],['compatibility','chip','violet','Windows & GPU','Wine, DXR and RTX tools'],['ai','sparkle','rose','Zorix AI','Local model client',true],['settings','settings','gray','Settings','Make Zorix yours'],['glasslab','droplet','cyan','Glass Lab','Liquid glass controls'],['performance','pulse','blue','Live Activity','Processes and hardware'],['rustlab','code','mint','Rust Layer','Systems source and status'],['calculator','calculator','cyan','Calculator','Quick calculations'],['focus','moon','violet','Focus','One thing at a time'],['calendar','clock','mint','Calendar','A little perspective'],['system','info','blue','System','Swift-powered insights'],['activity','layers','gray','Activity','Recent local actions'],['support','shield','mint','Support & Recovery','Boot and display diagnostics'],['about','shield','gray','About','Know your system']];
function allApps(){return builtInApps.concat(discoveredApps)}
function launcherGrid(query=''){return allApps().filter(a=>(a[3]+' '+a[4]).toLowerCase().includes(query.toLowerCase())).map(a=>`<button class="panel-tile" ${a[5]?'data-app':'data-panel'}="${esc(a[0])}"><span class="appicon ${a[2]}" data-icon="${a[1]}"></span><strong>${esc(a[3])}</strong><small>${esc(a[4])}</small></button>`).join('')||'<div class="empty">No matching applications.</div>'}
async function refreshApps(){try{const r=await api('apps'),known=new Set(builtInApps.map(a=>a[3].toLowerCase()));discoveredApps=(r.apps||[]).filter(x=>x&&x.id&&x.name&&!known.has(String(x.name).toLowerCase())).slice(0,80).map(x=>[String(x.id),'grid','soft',String(x.name),String(x.comment||'Installed application'),true]);syncDockApps();if(currentPanel==='launcher'&&$('#app-grid'))$('#app-grid').innerHTML=launcherGrid($('#app-search')?.value||'')}catch{}}
function syncDockApps(){const box=$('#dock-dynamic');if(!box)return;box.innerHTML=discoveredApps.slice(0,3).map(a=>`<button data-app="${esc(a[0])}" aria-label="${esc(a[3])}"><span class="appicon soft" data-icon="grid"></span><small>${esc(a[3])}</small></button>`).join('');icons()}
function setContent(html){$('#window-content').innerHTML=html;icons()}
function fmtBytes(n){n=Number(n||0);if(n>=1073741824)return (n/1073741824).toFixed(1)+' GiB';if(n>=1048576)return (n/1048576).toFixed(1)+' MiB';if(n>=1024)return (n/1024).toFixed(1)+' KiB';return n+' B'}
function settingToggle(key,title,description){return `<div class="settings-row"><div><strong>${title}</strong><small>${description}</small></div><button class="switch ${settings[key]?'on':''}" data-toggle="${key}" role="switch" aria-checked="${!!settings[key]}" aria-label="${title}"></button></div>`}
function settingsSidebar(){return `<aside class="settings-sidebar"><div class="settings-profile"><span class="settings-logo"><img src="assets/zorix-logo.svg" alt=""></span><div><strong>Zorix OS</strong><small>Glass Live 1.3.0</small></div></div>${[['appearance','droplet','Appearance'],['network','wifi','Network'],['bluetooth','bluetooth','Bluetooth'],['sound','volume','Sound'],['power','battery','Power'],['general','settings','General'],['accessibility','info','Accessibility'],['system','monitor','System'],['about','shield','About']].map(x=>`<button data-settings-section="${x[0]}" class="${currentSettingsSection===x[0]?'selected':''}">${icon(x[1])}<span>${x[2]}</span></button>`).join('')}</aside>`}
function appearanceSettings(){return `<h3 class="settings-title">Appearance</h3><p class="settings-lead">A lighter, faster glass surface with short spring motion.</p><div class="settings-group"><div class="theme-choice">${['aurora','dawn','midnight'].map(t=>`<button data-theme="${t}" class="${settings.theme===t?'selected':''}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><div class="slider-row"><div><strong>Glass intensity</strong><div class="body-small">Lower values use less blur and reduce GPU load.</div></div><input id="glass-intensity" type="range" min="35" max="85" value="${esc(settings.glassIntensity||64)}"><span class="slider-value" id="glass-value">${esc(settings.glassIntensity||64)}%</span></div>${settingToggle('wallpaperMotion','Living wallpaper','Optional slow wallpaper motion. Off by default for performance.')}${settingToggle('reducedTransparency','Reduce transparency','Use mostly solid surfaces.')}</div>`}
function generalSettings(){return `<h3 class="settings-title">General</h3><p class="settings-lead">Everyday Zorix preferences.</p><div class="settings-group"><div class="settings-row"><div><strong>Language</strong><small>Interface locale for dates and labels.</small></div><div class="segmented"><button data-language="en" class="${settings.language==='en'?'selected':''}">English</button><button data-language="it" class="${settings.language==='it'?'selected':''}">Italiano</button></div></div><div class="settings-row"><div><strong>Applications</strong><small>Browse all built-in and compatibility tools.</small></div><button class="pill" data-panel="launcher">Open Apps</button></div><div class="settings-row"><div><strong>Software Center</strong><small>Search packages and hand installs to ZPK/APT.</small></div><button class="pill" data-app="software">Open</button></div></div>`}
function networkSettings(){const n=connectivity.network||{};return `<h3 class="settings-title">Network</h3><p class="settings-lead">Real connection state from NetworkManager and Linux interfaces.</p><div class="settings-group"><div class="settings-row"><div><strong>${n.connected?'Connected':'Offline'}</strong><small>${esc(n.ssid||n.connection||n.interface||'No active connection')}</small></div><button class="pill" data-app="network">Open network settings</button></div><div class="settings-row"><div><strong>Wi-Fi</strong><small>${n.wifiEnabled===false?'Disabled':n.wifiPresent?'Available':'No wireless adapter detected'}</small></div><span class="status-chip">${n.defaultRoute?'Default route':'No route'}</span></div></div>`}
function bluetoothSettings(){const b=connectivity.bluetooth||{};return `<h3 class="settings-title">Bluetooth</h3><p class="settings-lead">Adapter state from BlueZ.</p><div class="settings-group"><div class="settings-row"><div><strong>${b.present?(b.powered?'Bluetooth On':'Bluetooth Off'):'No Bluetooth adapter'}</strong><small>${esc(b.adapter||'Hardware not detected')}</small></div><button class="pill" data-app="bluetooth">Open Bluetooth</button></div></div>`}
function soundSettings(){const a=connectivity.audio||{};return `<h3 class="settings-title">Sound</h3><p class="settings-lead">PipeWire/PulseAudio device and mixer access.</p><div class="settings-group"><div class="settings-row"><div><strong>${a.available?'Audio ready':'Audio service unavailable'}</strong><small>${esc(a.server||'No audio server detected')}</small></div><button class="pill" data-app="audio">Open mixer</button></div></div>`}
function powerSettings(){const b=connectivity.battery||{};return `<h3 class="settings-title">Power</h3><p class="settings-lead">Battery information from Linux power_supply.</p><div class="settings-group"><div class="settings-row"><div><strong>${b.present?(b.capacity+'% · '+b.status):'No battery detected'}</strong><small>${b.present?esc(b.name):'Desktop or battery data unavailable'}</small></div><span class="status-chip">${b.present?'Battery':'AC system'}</span></div></div>`}
function accessibilitySettings(){return `<h3 class="settings-title">Accessibility</h3><p class="settings-lead">Comfort options without changing the rest of the desktop.</p><div class="settings-group">${settingToggle('reducedMotion','Reduce motion','Shortens or disables spring transitions.')}${settingToggle('contrast','Increase contrast','Stronger borders and secondary text.')}${settingToggle('largeText','Larger text','Increase important interface text sizes.')}</div>`}
function systemSettings(){const v=system.version||'1.3.0',runtime=system.runtime||'Zorix Core';return `<h3 class="settings-title">System</h3><p class="settings-lead">Hardware and runtime status.</p><div class="settings-group"><div class="settings-hero"><span class="settings-logo large"><img src="assets/zorix-logo.svg" alt=""></span><div><strong>Zorix OS ${esc(v)}</strong><small>${esc(system.kernel||'Linux')} · ${esc(system.platform||'x86-64')}</small></div></div><div class="settings-row"><div><strong>Runtime</strong><small>${esc(runtime)}</small></div><button class="pill" data-panel="system">Details</button></div><div class="settings-row"><div><strong>Activity Monitor</strong><small>Inspect load, memory and processes.</small></div><button class="pill" data-app="monitor">Open</button></div><div class="settings-row"><div><strong>Recovery</strong><small>Boot, display and component diagnostics.</small></div><button class="pill" data-panel="support">Open</button></div></div>`}
function aboutSettings(){return `<h3 class="settings-title">About Zorix</h3><div class="settings-about"><img src="assets/zorix-logo.svg" alt="Zorix"><strong>Zorix OS 1.3.0 Glass</strong><span>Debian/Linux base · Swift Core · Rust source layer</span><small>Experimental x86-64 Live edition. UEFI only; Secure Boot is not validated.</small></div>`}
async function showSettings(section=currentSettingsSection){currentSettingsSection=section;if((section==='system'||section==='about')&&!system.version){try{system=await api('system')}catch{}}if(['network','bluetooth','sound','power'].includes(section)){try{connectivity=await api('connectivity')}catch{}}const pane=section==='appearance'?appearanceSettings():section==='network'?networkSettings():section==='bluetooth'?bluetoothSettings():section==='sound'?soundSettings():section==='power'?powerSettings():section==='general'?generalSettings():section==='accessibility'?accessibilitySettings():section==='system'?systemSettings():aboutSettings();setContent(`<div class="settings-shell">${settingsSidebar()}<section class="settings-main">${pane}<p class="settings-footnote">Preferences are stored locally. The Live edition remains volatile at shutdown.</p></section></div>`);const r=$('#glass-intensity');if(r){r.oninput=()=>{$('#glass-value').textContent=r.value+'%';document.documentElement.style.setProperty('--glass-opacity',String(Math.max(.42,Number(r.value)/100)));document.documentElement.style.setProperty('--glass-blur',`${Math.round(8+Number(r.value)*.12)}px`)};r.onchange=()=>updateSettings({glassIntensity:Number(r.value)}).catch(e=>toast(e.message))}}
async function panel(name){const opening=$('#overlay').classList.contains('hidden');currentPanel=name;$('#window-title').textContent=titles[name]||name;if(opening)resetWindowPosition();$('#overlay').classList.remove('hidden');setContent('<div class="empty">Opening...</div>');try{
 if(name==='launcher'){await refreshApps();setContent('<input class="field" id="app-search" placeholder="Search apps, tools and settings" autocomplete="off" aria-label="Search applications"><div class="panel-grid" id="app-grid" style="margin-top:14px">'+launcherGrid()+'</div>');$('#app-search').addEventListener('input',e=>$('#app-grid').innerHTML=launcherGrid(e.target.value));$('#app-search').focus()}
 else if(name==='files')await showFiles();
 else if(name==='notes'){const n=await api('notes');setContent('<h3 class="panel-heading">Thoughts, without clutter.</h3><p class="panel-intro">Saved to Documents / Zorix Notes.txt. The Live edition is volatile, so export anything you want to keep.</p><textarea class="notearea" id="note" spellcheck="false" aria-label="Your note"></textarea><div class="toolbar" style="margin-top:15px;margin-bottom:0"><span class="label" id="note-status">Ready</span><span class="spacer"></span><button class="pill" id="export-note">Export .txt</button><button class="primary" id="save-note">Save note</button></div>');$('#note').value=n.text;$('#save-note').onclick=saveNote;$('#note').oninput=()=>{$('#note-status').textContent='Unsaved changes'};$('#export-note').onclick=()=>{const u=URL.createObjectURL(new Blob([$('#note').value],{type:'text/plain'}));const a=document.createElement('a');a.href=u;a.download='Zorix Notes.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}}
 else if(name==='tasks')await showTasks();
 else if(name==='settings'){await showSettings()}
 else if(name==='glasslab'){setContent('<h3 class="panel-heading">Liquid, not flat.</h3><p class="panel-intro">Zorix Glass is an original CSS/Web compositor surface: multi-layer translucency, specular highlights, caustics, saturation and depth. It does not ship Apple Liquid Glass code.</p><div class="glass-demo"><div class="glass-orb"></div></div><div class="badges"><span>BACKDROP BLUR</span><span>SPECULAR LAYERS</span><span>CAUSTICS</span><span>POINTER LENS</span><span>REDUCED MOTION</span></div><div class="panel-grid"><button class="panel-tile" data-panel="settings">'+icon('settings')+'<strong>Material settings</strong><small>Intensity, motion and contrast</small></button><button class="panel-tile" data-theme="aurora">'+icon('droplet')+'<strong>Aurora</strong><small>Cool teal and violet</small></button><button class="panel-tile" data-theme="midnight">'+icon('moon')+'<strong>Midnight</strong><small>Low-light glass</small></button></div>')}
 else if(name==='control'){const [st,co]=await Promise.all([api('system'),api('connectivity')]);system=st;connectivity=co;const n=co.network||{},bt=co.bluetooth||{},au=co.audio||{},ba=co.battery||{};setContent('<h3 class="panel-heading">Control Center</h3><p class="panel-intro">Live hardware state with direct access to Debian managers.</p><div class="connectivity-grid"><div class="status-card"><span class="status-icon">'+icon('wifi')+'</span><div><strong>'+(n.connected?'Network connected':'Network offline')+'</strong><small>'+esc(n.ssid||n.connection||n.interface||'No active interface')+'</small></div><button class="pill" data-app="network">Open</button></div><div class="status-card"><span class="status-icon">'+icon('bluetooth')+'</span><div><strong>'+(bt.present?(bt.powered?'Bluetooth On':'Bluetooth Off'):'No Bluetooth')+'</strong><small>'+esc(bt.adapter||'No adapter detected')+'</small></div><button class="pill" data-app="bluetooth">Open</button></div><div class="status-card"><span class="status-icon">'+icon('volume')+'</span><div><strong>'+(au.available?'Audio ready':'Audio unavailable')+'</strong><small>'+esc(au.server||'No audio server')+'</small></div><button class="pill" data-app="audio">Mixer</button></div><div class="status-card"><span class="status-icon">'+icon('battery')+'</span><div><strong>'+(ba.present?(ba.capacity+'% · '+ba.status):'AC powered')+'</strong><small>'+(ba.present?esc(ba.name):'No battery detected')+'</small></div><button class="pill" data-settings-section="power">Details</button></div></div>'+settingToggle('reducedTransparency','Clear or tinted','Choose liquid glass or a more opaque surface.')+settingToggle('reducedMotion','Interface motion','Reduce animation and parallax.')+'<div class="toolbar"><button class="pill" data-panel="performance">Live activity</button><button class="pill" data-panel="system">System details</button><span class="spacer"></span><button class="pill" data-power="reboot">Restart</button><button class="pill" data-power="poweroff">Shut down</button></div>')} else if(name==='performance')await showPerformance();
 else if(name==='activity')await showActivity();
 else if(name==='rustlab')await showRust();
 else if(name==='support'){system=await api('system');const ds=system.displayStack||{};setContent('<h3 class="panel-heading">Support & recovery.</h3><p class="panel-intro">1.3.0 adds bounded Xorg fallback and a lower-cost boot splash.</p><div class="info-table">'+[['Platform',system.platform||'unknown'],['Xvfb',ds.Xvfb?'available':'missing'],['Xorg',ds.Xorg?'available':'missing'],['Openbox',ds.openbox?'available':'missing'],['Chromium',ds.chromium?'available':'missing'],['Portable display','Xvfb + framebuffer bridge'],['Recovery command','zorix-doctor'],['VM memory','8 GiB recommended; lower-memory boot unvalidated']].map(r=>'<div>'+esc(r[0])+'</div><div>'+esc(r[1])+'</div>').join('')+'</div><div class="notice">If the desktop exits, the recovery shell now has a real controlling TTY. Run <code>zorix-doctor</code> to show display, virtualization and recent Zorix logs.</div><button class="pill" data-app="terminal">Open Terminal</button>')}
 else if(name==='compatibility'){setContent('<h3 class="panel-heading">Play, with the facts.</h3><p class="panel-intro">Windows compatibility and GPU tooling are managed here without invented support percentages.</p><div class="compat-card"><strong>Windows applications</strong><p>Wine runtime: <b>'+ (system.wineInstalled?'detected':'not bundled / not detected')+'</b>. Prefix management, backups, component import and diagnosis are available through Windows Center.</p><button class="pill" data-app="windows">Open Windows Center</button></div><div class="compat-card"><strong>Game graphics</strong><p>NVIDIA driver: <b>'+(system.nvidiaDriverPresent?'detected':'not detected')+'</b>. Ray tracing and DLSS integration are <b>off by default</b> in Zorix. They will be explicit opt-in controls in the Game Bar after the real driver/runtime path is validated.</p><button class="pill" data-app="gpu">Open GPU / RTX Center</button></div><div class="notice">This Live ISO does not bundle NVIDIA proprietary drivers, Wine, DXVK, VKD3D-Proton or AI model weights. RTX support still depends on the actual GPU, Vulkan driver, compatibility layer and application.</div>')}
 else if(name==='system'){system=await api('system');const rust=system.rust||{};setContent('<h3 class="panel-heading">Under the glass.</h3><p class="panel-intro">Read-only system facts from the compiled Swift Zorix Core plus the 1.3.0 systems layer and refreshed desktop shell.</p><div class="info-table">'+[['System','Zorix OS '+system.version],['Base','Debian GNU/Linux 13'],['Kernel',system.kernel||'Unavailable'],['Processor',system.cpuModel||'Unavailable'],['Logical CPUs',system.logicalCPUs||'--'],['Memory',((system.memoryTotalKiB||0)/1048576).toFixed(2)+' GiB'],['Uptime',Math.floor((system.uptimeSeconds||0)/60)+' minutes'],['Swift core',system.runtime||'Unavailable'],['Rust layer',rust.binaryAvailable?'compiled binary available':'source integrated; binary not compiled in this build'],['Platform',system.platform||'unknown'],['Storage',system.storagePersistence],['Home free',fmtBytes(system.homeStorage?.freeBytes)],['Graphics validation','Not performed on real hardware']].map(r=>'<div>'+esc(r[0])+'</div><div>'+esc(r[1])+'</div>').join('')+'</div>')}
 else if(name==='about'||name==='welcome'){setContent('<div class="center"><span class="orbit-mark" style="margin:0 auto 20px;width:76px;height:76px;border-radius:24px"><i style="font-size:45px">Z</i></span><h3 class="panel-heading">Zorix OS. Light becomes a workspace.</h3><p class="panel-intro" style="margin-left:auto;margin-right:auto">Glass Live 1.3.0 · Experimental x86-64 edition<br>Design direction: Gabriele Aeng</p></div><div class="badges"><span>ZORIX LIQUID GLASS</span><span>SWIFT USER-SPACE CORE</span><span>RUST SYSTEMS SOURCE</span><span>C UEFI LOADER</span><span>LINUX / DEBIAN BASE</span></div><div class="panel-grid"><button class="panel-tile" data-panel="glasslab">'+icon('droplet')+'<strong>Liquid material</strong><small>Depth, refraction-like layers and motion</small></button><button class="panel-tile" data-panel="performance">'+icon('pulse')+'<strong>Live activity</strong><small>Read-only process and hardware data</small></button><button class="panel-tile" data-panel="rustlab">'+icon('code')+'<strong>Rust layer</strong><small>Source and reproducible build status</small></button></div><p class="notice">The visual shell is original and glass-inspired; it does not include Apple SwiftUI, UIKit, AppKit, proprietary Liquid Glass code, Apple icons or Apple system fonts. The Linux kernel remains Debian-based and has not been rewritten.</p><p class="body-small">Live mode runs from memory and does not automatically mount or erase internal disks. The Calamares installer is experimental and the full install/reboot chain is still being validated.</p>')}
 else if(name==='focus'){setContent('<h3 class="panel-heading center">One thing at a time.</h3><p class="panel-intro center">A 25-minute focus timer. It stays active while this desktop is open.</p><div class="big-number" id="focus-time"></div><div class="center"><button class="primary" id="focus-toggle">'+(focusRunning?'Pause':'Start focus')+'</button> <button class="pill" id="focus-reset">Reset</button></div>');$('#focus-toggle').onclick=()=>{focusRunning=!focusRunning;if(focusRunning)focusDeadline=Date.now()+focusRemaining*1000;$('#focus-toggle').textContent=focusRunning?'Pause':'Start focus';tickFocus()};$('#focus-reset').onclick=()=>{focusRunning=false;focusRemaining=1500;$('#focus-toggle').textContent='Start focus';tickFocus()};tickFocus()}
 else if(name==='calculator'){setContent('<div class="calculator"><input class="field calc-display" id="calc" value="'+esc(calc)+'" placeholder="0" aria-label="Expression"><div class="calc-keys">'+['C','(',')','/','7','8','9','*','4','5','6','-','1','2','3','+','0','.','Del','='].map(k=>'<button data-calc="'+k+'">'+k+'</button>').join('')+'</div><p class="body-small">Supports parentheses and + - * /. Expressions are parsed, never executed as code.</p></div>');$('#calc').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();calcKey('=')}})}
 else if(name==='calendar'){const now=new Date(),first=new Date(now.getFullYear(),now.getMonth(),1).getDay(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();setContent('<h3 class="panel-heading">'+esc(now.toLocaleDateString(settings.language==='it'?'it':'en',{month:'long',year:'numeric'}))+'</h3><div class="calendar-grid">'+['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>'<span class="day-head">'+d+'</span>').join('')+Array(first).fill('<span></span>').join('')+Array.from({length:days},(_,i)=>`<span class="${i+1===now.getDate()?'today':''}">${i+1}</span>`).join('')+'</div><p class="body-small">Uses the local system clock. No cloud calendar or account synchronization is connected.</p>')}
 else setContent('<div class="empty">Panel not available.</div>');
 }catch(e){setContent('<div class="notice">'+esc(e.message)+'</div>')}}
async function showTasks(){const r=await api('tasks'),tasks=r.tasks||[];setContent('<h3 class="panel-heading">Flow Board</h3><p class="panel-intro">A tiny local task list for the current Zorix home. No cloud account, synchronization or analytics.</p><div class="task-add"><input class="field" id="task-input" maxlength="180" placeholder="What is the next small thing?"><button class="primary" id="task-add">Add</button></div><div class="task-list" id="task-list">'+taskMarkup(tasks)+'</div><p class="body-small">In the Live edition these tasks disappear at shutdown unless the home folder is persisted externally.</p>');$('#task-add').onclick=()=>taskAction('add',{text:$('#task-input').value});$('#task-input').onkeydown=e=>{if(e.key==='Enter')taskAction('add',{text:e.target.value})}}
function taskMarkup(tasks){return tasks.length?tasks.map(t=>`<div class="task-row ${t.done?'done':''}"><button class="task-check ${t.done?'done':''}" data-task-toggle="${esc(t.id)}" aria-label="Toggle task">${t.done?icon('check'):''}</button><span class="task-text">${esc(t.text)}</span><button class="task-delete" data-task-delete="${esc(t.id)}" aria-label="Delete task">${icon('trash')}</button></div>`).join(''):'<div class="task-empty">Your flow is clear.</div>'}
async function taskAction(action,extra){try{const r=await api('tasks',{action,...extra});if($('#task-list'))$('#task-list').innerHTML=taskMarkup(r.tasks||[]);if($('#task-input'))$('#task-input').value='';toast(action==='add'?'Task added':'Flow updated')}catch(e){toast(e.message)}}
async function showPerformance(){const [p,h,s]=await Promise.all([api('processes'),api('hardware'),api('system')]);system=s;const total=s.memoryTotalKiB||1,used=total-(s.memoryAvailableKiB||0),load=s.loadAverage||'n/a';const gpus=h.gpus||[],bats=h.batteries||[],temps=h.temperatures||[];setContent('<h3 class="panel-heading">Live activity.</h3><p class="panel-intro">Read-only process and hardware facts from Linux. No process termination or privileged controls are exposed here.</p><div class="resource-grid"><div class="resource-card"><span>MEMORY</span><strong>'+esc((used/1048576).toFixed(1))+' GiB</strong></div><div class="resource-card"><span>LOGICAL CPU</span><strong>'+esc(s.logicalCPUs||'--')+'</strong></div><div class="resource-card"><span>LOAD AVG</span><strong>'+esc(load)+'</strong></div></div><div class="hardware-list">'+(gpus.length?gpus.map(g=>`<div class="hardware-card"><strong>${esc(g.card)} · ${esc(g.driver)}</strong><small>Vendor ${esc(g.vendor||'?')} · Device ${esc(g.device||'?')}</small></div>`).join(''):'<div class="hardware-card"><strong>GPU</strong><small>No DRM card reported in this environment.</small></div>')+(bats.length?bats.map(b=>`<div class="hardware-card"><strong>${esc(b.name)} · ${esc(b.capacity)}%</strong><small>${esc(b.status)}</small></div>`).join(''):'')+(temps.length?`<div class="hardware-card"><strong>Thermals</strong><small>${temps.slice(0,4).map(t=>esc(t.name)+' '+esc(t.celsius)+'°C').join(' · ')}</small></div>`:'')+'</div><h3 class="panel-heading" style="font-size:17px;margin-top:20px">Top memory processes</h3><div class="process-list"><div class="process-head"><span>PID</span><span>PROCESS</span><span>MEMORY</span><span>THREADS</span></div>'+(p.processes||[]).slice(0,18).map(x=>`<div class="process-row"><span>${esc(x.pid)}</span><span>${esc(x.name)}</span><span>${fmtBytes((x.rssKiB||0)*1024)}</span><span>${esc(x.threads)}</span></div>`).join('')+'</div>')}
async function showActivity(){const r=await api('events'),events=(r.events||[]).slice().reverse();setContent('<h3 class="panel-heading">Recent activity.</h3><p class="panel-intro">Only coarse local actions from this shell session are shown. Note contents, tokens and private filenames are not recorded here.</p><div class="activity-list">'+(events.length?events.map(e=>`<div class="activity-row"><i></i><span>${esc(String(e.action||'activity').replaceAll('-',' '))}</span><small>${new Date((e.time||0)*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div>`).join(''):'<div class="empty">No shell actions yet.</div>')+'</div>')}
async function showRust(){system=await api('system');const r=system.rust||{};const src=`use std::fs;\n\nfn kernel() -> String {\n    fs::read_to_string(\"/proc/sys/kernel/osrelease\")\n        .unwrap_or_default()\n        .trim().to_string()\n}\n\nfn main() {\n    // Zorix Runtime Core 1.2\n    // Reads Linux system facts without external crates.\n}`;setContent('<h3 class="panel-heading">Rust systems layer.</h3><p class="panel-intro">Zorix 1.2 includes a dependency-free Rust systems probe source and a reproducible build target alongside the existing compiled Swift core.</p><div class="badges"><span>RUST SOURCE INTEGRATED</span><span>NO EXTERNAL CRATES</span><span>READ-ONLY /PROC</span></div><div class="compat-card"><strong>Build status</strong><p>'+(r.binaryAvailable?'A compiled <code>zorix-rust-core</code> binary is present in this build.':'The Rust source is included, but the artifact build environment did not have <code>rustc</code>; therefore this ISO does not pretend the Rust binary was compiled.')+'</p><span class="status-chip">'+(r.binaryAvailable?'Compiled runtime':'Source-only build')+'</span></div><div class="rust-code">'+esc(src)+'</div><p class="body-small">Source path in the image: /usr/share/doc/zorix-os/source/ZorixRuntime.rs. Build command: rustc -O src/ZorixRuntime.rs -o bin/zorix-rust-core.</p>')}
async function showFiles(){const [f,v]=await Promise.all([api('files?root='+encodeURIComponent(currentFileRoot)+'&path='+encodeURIComponent(currentPath)),api('volumes')]);const roots=[['home','Home'],...(v.volumes||[]).map(x=>[x.id,x.name])];setContent('<div class="toolbar file-roots">'+roots.map(r=>'<button class="pill '+(currentFileRoot===r[0]?'selected':'')+'" data-file-root="'+esc(r[0])+'">'+esc(r[1])+'</button>').join('')+'<span class="spacer"></span><button class="pill" data-app="files">Full file manager</button></div><div class="toolbar"><button class="pill" id="up-folder">Up</button><span class="label">'+esc(roots.find(r=>r[0]===currentFileRoot)?.[1]||'Storage')+' / '+esc(f.path==='.'?'':f.path)+'</span><span class="spacer"></span>'+(currentFileRoot==='home'?'<button class="pill" id="new-folder">New folder</button>':'')+'</div><div class="itemlist">'+f.items.map(i=>`<button class="file-item" ${i.directory?'data-dir="'+esc(i.name)+'"':''}><span>${icon(i.directory?'folder':'file')}</span><span>${esc(i.name)}</span><small>${i.directory?'Folder':fmtBytes(i.size)}</small></button>`).join('')+'</div>'+(f.items.length?'':'<div class="empty">This folder is empty.</div>')+'<p class="body-small">Home and already mounted removable volumes are available. Hidden files are omitted.</p>');$('#up-folder').onclick=()=>{currentPath=currentPath.split('/').slice(0,-1).join('/');showFiles().catch(e=>toast(e.message))};const nf=$('#new-folder');if(nf)nf.onclick=()=>{const t=document.createElement('div');t.innerHTML='<div class="toolbar"><input class="field" id="folder-name" placeholder="New folder name" style="margin:0"><button class="primary" id="create-folder">Create</button></div>';$('#window-content').prepend(t);$('#folder-name').focus();$('#create-folder').onclick=async()=>{try{await api('mkdir',{path:currentPath,name:$('#folder-name').value});await showFiles()}catch(e){toast(e.message)}}}}
async function saveNote(){try{await api('notes',{text:$('#note').value});$('#note-status').textContent='Saved locally';toast('Note saved')}catch(e){toast(e.message)}}
function calculate(text){const tokens=text.match(/(?:\d+(?:\.\d*)?|\.\d+)|[()+\-*/]/g)||[];if(tokens.join('')!==text.replace(/\s/g,'')||tokens.length>150)throw Error('Invalid expression');let i=0;function atom(){let t=tokens[i++];if(t==='-')return -atom();if(t==='+')return atom();if(t==='('){let v=sum();if(tokens[i++]!==')')throw Error('Missing )');return v}if(t===undefined||!/^\d|^\./.test(t))throw Error('Expected a number');return Number(t)}function product(){let v=atom();while(tokens[i]==='*'||tokens[i]==='/'){let op=tokens[i++],n=atom();v=op==='*'?v*n:v/n}return v}function sum(){let v=product();while(tokens[i]==='+'||tokens[i]==='-'){let op=tokens[i++],n=product();v=op==='+'?v+n:v-n}return v}let result=sum();if(i!==tokens.length||!Number.isFinite(result))throw Error('Undefined result');return Number(result.toPrecision(12))}
function calcKey(k){const input=$('#calc');if(!input)return;calc=input.value;if(k==='C')calc='';else if(k==='Del')calc=calc.slice(0,-1);else if(k==='='){try{calc=String(calculate(calc))}catch(e){toast(e.message);return}}else calc+=k;input.value=calc}
function tickFocus(){if(focusRunning){focusRemaining=Math.max(0,Math.ceil((focusDeadline-Date.now())/1000));if(!focusRemaining){focusRunning=false;toast('Focus complete.');if($('#focus-toggle'))$('#focus-toggle').textContent='Start focus'}}const t=String(Math.floor(focusRemaining/60)).padStart(2,'0')+':'+String(focusRemaining%60).padStart(2,'0');if($('#focus-time'))$('#focus-time').textContent=t;if($('#focus-mini'))$('#focus-mini').textContent=focusRunning?t+' remaining':'Find your rhythm'}
function tick(){const d=new Date(),locale=settings.language==='it'?'it-IT':'en-GB',time=d.toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit'});$('#clock').textContent=d.toLocaleDateString(locale,{weekday:'short'})+' '+time;$('#big-clock').textContent=time;$('#day').textContent=d.toLocaleDateString(locale,{weekday:'long'}).toUpperCase();$('#date').textContent=d.toLocaleDateString(locale,{month:'long',day:'numeric'});tickFocus()}
async function refreshSystem(){try{system=await api('system');const total=system.memoryTotalKiB||1,used=total-(system.memoryAvailableKiB||0);$('#memory').textContent=(used/1048576).toFixed(1)+' / '+(total/1048576).toFixed(1)+' GiB';$('#memory-bar').style.width=(used/total*100)+'%';$('#cpu').textContent=(system.logicalCPUs||'--')+' logical CPUs';$('#health-text').textContent=system.runtime?.startsWith('Swift')?'Zorix Core is connected':'System information unavailable';$('#runtime').textContent=system.runtime||'Core unavailable';if($('#rust-mini'))$('#rust-mini').textContent=system.rust?.binaryAvailable?'Compiled runtime':'Source integrated'}catch(e){$('#health-text').textContent='Session disconnected'}}
function updateStatusBar(){const n=connectivity.network||{},bt=connectivity.bluetooth||{},au=connectivity.audio||{},ba=connectivity.battery||{};const w=$('#wifi-status'),b=$('#bluetooth-status'),a=$('#audio-status'),bat=$('#battery-status');if(w){w.classList.toggle('offline',!n.connected);const x=w.querySelector('small');if(x)x.textContent=n.ssid||n.connection||(n.connected?'On':'Off')}if(b)b.classList.toggle('offline',!bt.present||!bt.powered);if(a)a.classList.toggle('offline',!au.available);if(bat){bat.classList.toggle('hidden-status',!ba.present);const x=bat.querySelector('small');if(x)x.textContent=ba.present?ba.capacity+'%':'--'}}
async function refreshConnectivity(){try{connectivity=await api('connectivity');updateStatusBar()}catch{}}
let windowX=0,windowY=0,dragState=null,dragFrame=0;
function resetWindowPosition(){windowX=0;windowY=0;const w=$('#window');if(w)w.style.transform='translate3d(0,0,0)'}
function initWindowDrag(){const handle=$('#window-drag-handle'),w=$('#window');if(!handle||!w)return;handle.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('.window-controls,button,input,textarea'))return;dragState={id:e.pointerId,x:e.clientX,y:e.clientY,ox:windowX,oy:windowY};w.classList.add('dragging');handle.setPointerCapture?.(e.pointerId);e.preventDefault()});handle.addEventListener('pointermove',e=>{if(!dragState||dragState.id!==e.pointerId)return;const maxX=Math.max(0,(window.innerWidth-140)/2),maxY=Math.max(0,(window.innerHeight-110)/2);windowX=Math.max(-maxX,Math.min(maxX,dragState.ox+e.clientX-dragState.x));windowY=Math.max(-maxY,Math.min(maxY,dragState.oy+e.clientY-dragState.y));if(!dragFrame)dragFrame=requestAnimationFrame(()=>{dragFrame=0;w.style.transform=`translate3d(${windowX}px,${windowY}px,0)`})});const stop=e=>{if(!dragState||dragState.id!==e.pointerId)return;dragState=null;w.classList.remove('dragging');try{handle.releasePointerCapture(e.pointerId)}catch{}};handle.addEventListener('pointerup',stop);handle.addEventListener('pointercancel',stop)}
function closePanel(){$('#overlay').classList.add('hidden');currentPanel='';resetWindowPosition()}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.panel)await panel(b.dataset.panel);else if(b.dataset.app)await launch(b.dataset.app);else if(b.dataset.toggle){const k=b.dataset.toggle;await updateSettings({[k]:!settings[k]});b.classList.toggle('on',settings[k]);b.setAttribute('aria-checked',settings[k])}else if(b.dataset.settingsSection){await showSettings(b.dataset.settingsSection)}else if(b.dataset.language){await updateSettings({language:b.dataset.language});await showSettings('general')}else if(b.dataset.theme){await updateSettings({theme:b.dataset.theme});if(currentPanel==='settings')await showSettings('appearance');else toast('Theme changed')}else if(b.dataset.fileRoot){currentFileRoot=b.dataset.fileRoot;currentPath='';await showFiles()}else if(b.dataset.dir){currentPath=[currentPath,b.dataset.dir].filter(Boolean).join('/');await showFiles()}else if(b.dataset.calc)calcKey(b.dataset.calc);else if(b.dataset.taskToggle)await taskAction('toggle',{id:b.dataset.taskToggle});else if(b.dataset.taskDelete)await taskAction('delete',{id:b.dataset.taskDelete});else if(b.dataset.power){const a=b.dataset.power;setContent('<h3 class="panel-heading">'+(a==='reboot'?'Restart Zorix?':'Shut down Zorix?')+'</h3><p class="notice">Unsaved files and all Live-session changes will be lost. Export important files first.</p><button class="primary" id="confirm-power">Confirm '+a+'</button> <button class="pill" data-panel="control">Cancel</button>');$('#confirm-power').onclick=async()=>{try{await api('power',{action:a,confirmation:a});toast('Power action requested')}catch(e){toast(e.message)}}}}catch(e){toast(e.message)}});
$('#close').onclick=closePanel;$('#overlay').addEventListener('click',e=>{if(e.target===$('#overlay'))closePanel()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanel();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();panel('launcher')}});
function bootGlass(){
  try{
    icons();
    initWindowDrag();
    tick();
    setTimeout(()=>{
      const root=document.documentElement;
      const body=document.body;
      if(!root||!body||!$('#dock')||!$('#clock')){reportStartupError('ready-dom',new Error('Required desktop DOM is incomplete'));return}
      api('ready',{render:renderMode}).then(()=>{
        root.dataset.glassReady='true';
        let beat=0;
        setInterval(()=>api('heartbeat',{beat:++beat,render:renderMode}).catch(()=>{}),3000);
      }).catch(e=>reportStartupError('ready',e));
    },1200);
  }catch(e){
    reportStartupError('bootstrap',e);
    document.body.classList.add('bootstrap-failed');
  }
  setInterval(()=>{try{tick()}catch(e){reportStartupError('clock',e)}},1000);
  api('settings').then(v=>{settings=v;applySettings();tick()}).catch(e=>toast(e.message));
  setTimeout(()=>refreshSystem(),0);setInterval(refreshSystem,30000);
  setTimeout(()=>refreshConnectivity(),250);setInterval(refreshConnectivity,15000);
  setTimeout(()=>refreshApps(),500);setInterval(refreshApps,60000);
  window.zorixCalculate=calculate;
}
bootGlass();
