displaymanagers: [ lightdm ]
defaultDesktopEnvironment:
  executable: "/usr/bin/zorix-session-supervisor"
  desktopFile: "zorix"
basicSetup: false
sysconfigSetup: false
lightdm:
  preferred_greeters: [ "lightdm-gtk-greeter.desktop" ]
