dontChroot: false
timeout: 120
verbose: true
script:
  - "systemctl set-default graphical.target"
  - "-systemctl enable lightdm.service"
  - "-systemctl enable NetworkManager.service"
  - "-systemctl enable bluetooth.service"
  - "-systemctl enable fstrim.timer"
  - "-systemctl enable systemd-timesyncd.service"
  - "-update-initramfs -u -k all"
  - "-rm -f /usr/share/applications/zorix-installer.desktop /usr/bin/zorix-installer"
  - "-rm -rf /etc/calamares"
  - "printf 'GRUB_TIMEOUT=3\nGRUB_TIMEOUT_STYLE=menu\nGRUB_CMDLINE_LINUX_DEFAULT=\"quiet loglevel=3\"\n' > /etc/default/grub"
i18n:
  name: "Finalizing Zorix OS"
