unpack:
  - source: "/"
    sourcefs: "file"
    destination: ""
    exclude:
      - "/dev/*"
      - "/proc/*"
      - "/sys/*"
      - "/run/*"
      - "/tmp/*"
      - "/mnt/*"
      - "/media/*"
      - "/lost+found"
      - "/home/zorix/.cache/*"
      - "/home/zorix/Downloads/*"
      - "/var/log/*"
      - "/var/tmp/*"
      - "/var/cache/apt/archives/*"
    weight: 10
